apiVersion: apps/v1
kind: Deployment
metadata:
  name: stocktrader-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: stocktrader-operator
  template:
    metadata:
      labels:
        name: stocktrader-operato
    spec:
      serviceAccountName: stocktrader-operator
      containers:
        - name: stocktrader-operator
          # Replace this with the built image name
          image: slombardo2/stocktrader-operator:latest
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "stocktrader-operator"
